title: Document Freedom Day (DFD)
description: Document Freedom Day is a worldwide celebration of open document formats, open standards and related technologies.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
